declare -fr ask::yes
declare -fr ask::no
declare -fr ask::sudo
declare -fr color::black
declare -fr color::red
declare -fr color::green
declare -fr color::yellow
declare -fr color::blue
declare -fr color::purple
declare -fr color::cyan
declare -fr color::white
declare -fr color::bblack
declare -fr color::bred
declare -fr color::bgreen
declare -fr color::byellow
declare -fr color::bblue
declare -fr color::bpurple
declare -fr color::bcyan
declare -fr color::bwhite
declare -fr color::iblack
declare -fr color::ired
declare -fr color::igreen
declare -fr color::iyellow
declare -fr color::iblue
declare -fr color::ipurple
declare -fr color::icyan
declare -fr color::iwhite
declare -fr color::off
declare -fr crypto::bytes
declare -fr crypto::num
declare -fr date::unix::translate
declare -fr date::unix
declare -fr date::time
declare -fr date::calendar
declare -fr date::now
declare -fr date::year
declare -fr date::month
declare -fr date::day
declare -fr date::hour
declare -fr date::minute
declare -fr date::second
declare -fr hash::md5
declare -fr hash::sha1
declare -fr hash::sha256
declare -fr hash::sha512
declare -fr log::dot
declare -fr log::prog
declare -fr log::tab
declare -fr log::ok
declare -fr log::info
declare -fr log::warn
declare -fr log::fail
declare -fr log::danger
declare -fr panic
declare -fr ___BEGIN___ERROR___TRACE___
declare -fr ___ENDOF___ERROR___TRACE___
